name: "دانلودر لینک مستقیمv2"

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: "Direct File URL"
        required: true
        type: string

permissions:
  contents: write

jobs:
  direct-download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y curl

      - name: Download File
        id: download
        run: |
          mkdir -p temp_dl
          FILE_URL="${{ github.event.inputs.file_url }}"

          FILENAME=$(basename "$FILE_URL" | cut -d'?' -f1)
          FILENAME=$(echo "$FILENAME" | sed 's/[^a-zA-Z0-9._() -]/_/g')

          curl -L --fail --retry 3 -o "temp_dl/$FILENAME" "$FILE_URL"

          echo "filename=$FILENAME" >> $GITHUB_OUTPUT

      - name: Split File if Larger Than 100MB
        run: |
          cd temp_dl

          FILE="${{ steps.download.outputs.filename }}"
          SIZE=$(stat -c%s "$FILE")

          LIMIT=$((100*1024*1024))

          if [ "$SIZE" -gt "$LIMIT" ]; then
            echo "File larger than 100MB. Splitting..."

            split -b 95M -d -a 3 \
            --additional-suffix=.mp4 \
            "$FILE" "${FILE%.mp4}.part"

            rm "$FILE"
          else
            echo "File under limit, no split needed"
          fi

          cd ..

      - name: Push Parts to Repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"

          mkdir -p downloads
          mv temp_dl/* downloads/

          git add downloads/
          git commit -m "Uploaded split video parts [skip ci]" || echo "No changes"

          git push

      - name: Cleanup
        if: always()
        run: rm -rf temp_dl
